apiVersion: v1
kind: Service
metadata:
  labels:
    app: netflix-svc
  name: netflix-svc
spec:
  type: ClusterIP
  ports:
    - name: netflix-svc-port
      port: 80
      targetPort: 80
  selector:
    app: netflix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netflix-deploy
  name: netflix-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - image: sevenajay/netflix
          name: netflix
