apiVersion: v1
kind: Service
metadata:
  name: result-svc
  labels:
    app: result-svc
spec:
  type: NodePort
  ports:
    - name: result-svc-port
      port: 5001
      targetPort: result-port
      nodePort: 32001
  selector:
    app: result
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deploy
  labels:
    app: result-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - image: eyodevops/voting-app-result:v1
          name: result
          ports:
            - containerPort: 80
              name: result-port
