apiVersion: v1
kind: Service
metadata:
  labels:
    app: tetris-svc
  name: tetris-svc
spec:
  type: NodePort
  ports:
    - name: tetris-svc-port
      port: 5005
      targetPort: 80
      nodePort: 31006
  selector:
    app: tetris
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tetris-deploy
  name: tetris-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
        - image: lrakai/tetris
          name: tetris
